user root;
worker_processes 1;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log warn;

events { worker_connections 256; }

http {
    log_format hdr '$remote_addr "$request" $status accept="$http_accept" ua="$http_user_agent"';
    access_log /var/log/nginx/access.log hdr;
    sendfile on;
    keepalive_timeout 30;

    server {
        listen 443 ssl;
        server_name api.github.com github.com;

        ssl_certificate     /etc/ssl/fakegh/api.github.com.crt;
        ssl_certificate_key /etc/ssl/fakegh/api.github.com.key;

        location / {
            proxy_pass         http://127.0.0.1:4010;
            proxy_set_header   Host api.github.com;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_http_version 1.1;
        }
    }
}
